dist: bionic
language: java
env:
  - AWS_REGION=us-east-1
jdk:
  - openjdk11
services:
  - docker
before_install:
  - docker pull localstack/localstack
script:
  - mvn clean test
  - mvn clean integration-test