dist: bionic
language: java
env:
  - AWS_REGION=us-east-1
  - AWS_ACCESS_KEY_ID=AKXXXXXXXXXXXXXXX
  - AWS_SECRET_KEY=YYYYYYYYYYYYYYYYYY
jdk:
  - openjdk11
services:
  - docker
before_install:
  - docker pull localstack/localstack
script:
  - mvn clean test
  - mvn clean integration-test